### PR TITLE
[In Development] 1.13+ Changes

### PR DESCRIPTION
**Pull request by Xernium**
Currently some of this still breaks with the backwards compatability, will need resolving before this can be merged

### CODE REVIEW

**Comment by AmauryCarrade** [comment]
Hello! And sorry for the delay.

Due to conflicts and ongoing changes, I could not merge your pull request. This being said, **I added your fixes to zLib, with commits authored by you** (I used the same author as the commit of this PR).

These commits are from your work under your name: f556e5d537b1b0546e8a38f8ba867b7373697b0d ec5663cbfdd582335e01824a5ae7373c27524294 7bfd7902b1f1b1dad64af4be2569a8a0e00d31a8 a6dc778ab1d55ff6129a72f2ea3a27a04bca9436

And these ones are inspired from it but rewritten differently: eb7d15d3dbe646c31e48167c8990dc706ca4f676 6b6bc94dbb91467e657e9b63ce4ff15a07047549

Thanks a lot for your changes! I was slow to answer, but I appreciated them. If you don't want to be the author of the commits or want another author (the current one is not associated with your account), just ask ans I'll rewrite the history.

**Comment by Xernium** [comment]
@AmauryCarrade Thanks for returning to the project! If you fix the Inventory GUI's Ill gladly do a comprehensive real update for ImageOnMap for 1.13-1.14 that adds the new features

**Comment by AmauryCarrade** [comment]
o/

What are the bugs you mention on InventoryGUI? I added your changes to zLib but without intensive testing yet. In ImageOnMap, with the notable exception of the sign GUIs (due to the new Material), it worked pretty well. I may have been missing something?

On the ImageOnMap project itself, I already have a lot of non-published fixes (new APIs, map IDs as integers, …), and I think there isn't a lot of things left to do. Feel free to contribute through issues or pull requests—it would be appreciated—, but wait before I publish my commits :) .

13 novembre 2019 14:51 "Markus L. (Xer)" <notifications@github.com (mailto:notifications@github.com?to=%22Markus%20L.%20(Xer)%22%20<notifications@github.com>)> a écrit:
	@AmauryCarrade (https://github.com/AmauryCarrade) Thanks for returning to the project! If you fix the Inventory GUI's Ill gladly do a comprehensive real update for ImageOnMap for 1.13-1.14 that adds the new features

**Comment by Xernium** [comment]
@AmauryCarrade If you want Ill take a step directly towards 1.14+ here- There is now map locking and the rendering works slightly differently. As for the inventory- I don't recall what exactly it was- Yes the sign material is an issue, but that issue will appear again as it changes *yet again* in 1.14+. I think it was to do with GUI titles? Not sure- but I think 1.13+ (or was it 1.14+?) md_5 removed .getName() from inventories in favour of .getTitle() in active InventoryViews. However we can now use PersistentMetaData in 1.14 to store ID's that don't correspond to map ID's. I would just register a namespacedKey and use a UUID instead of the map integer ID in 1.14+. What do you think? Btw if you have discord feel free to add me by my tag: Five#3114

**Comment by AmauryCarrade** [comment]
> There is now map locking and the rendering works slightly differently.

Map locking could be useful, and it's really simple to add with zLib NBT APIs, so why not! For the rendering part, I don't use the native rendering but the Bukkit API, and this one wasn't changed so it's fine.

> Yes the sign material is an issue, but that issue will appear again as it changes yet again in 1.14+. 

The zLib fix should cover both 1.13 and 1.14 :)

> I think it was to do with GUI titles? Not sure- but I think 1.13+ (or was it 1.14+?) md_5 removed .getName() from inventories in favour of .getTitle() in active InventoryViews.

Yep, that's been fixed too (by yourself in fact :D)

> However we can now use PersistentMetaData in 1.14 to store ID's that don't correspond to map ID's. I would just register a namespacedKey and use a UUID instead of the map integer ID in 1.14+. What do you think?

Oh! I wasn't aware of this new API. That's pretty cool! I'll definitely look into that.

> Btw if you have discord feel free to add me by my tag

I do, you'll get a notification soon. :)

**Pull request closed without merging**
